Добавляет разметку главной страницы и каталога
htmlacademy-htmlcss/2315875-sedona-36 pull request #2
Opened 2023-01-25 21:20 UTC by oxxse

2023-01-26 08:12 UTC, vadimrahmanov requested changes
Отличная работа! Видно, что есть набор знаний и с вёрсткой сталкиваешься не первый раз. 

Имеется немного замечаний.
Если возникнут вопросы, ты знаешь, где меня найти.

2023-01-26 08:12 UTC, vadimrahmanov commented on index.html
> +    <meta charset="UTF-8" />
Не нужно закрывать `meta` тэги. Это не даёт никакого эффекта. Тоже самое скажет W3C Валидатор.

2023-01-26 08:12 UTC, vadimrahmanov commented on index.html
> +          <img src="" class="page-header-logo" alt="Логотип городка Седона." />
Не нужно закрывать `img` тэги.

2023-01-26 08:12 UTC, vadimrahmanov commented on index.html
> +      <img src="" alt="Добро пожаловать в Седону" />
Не нужно закрывать `img` тэги.

2023-01-26 08:12 UTC, vadimrahmanov commented on index.html
> +        <img src="" alt="Каньон" />
Не нужно закрывать `img` тэги.

2023-01-26 08:12 UTC, vadimrahmanov commented on index.html
> +          />
Не нужно закрывать `input` тэги тоже, они самозакрывающие.

2023-01-26 08:12 UTC, vadimrahmanov commented on index.html
> +          <img src="" alt="Логотоп HTML-Академии" />
Не нужно закрывать `img` тэги.

2023-01-26 08:12 UTC, vadimrahmanov commented on catalog.html
> +    <meta charset="UTF-8" />
Не нужно закрывать `meta` тэги.

2023-01-26 08:12 UTC, vadimrahmanov commented on catalog.html
> +          <img src="" class="page-header-logo" alt="Логотип городка Седона." />
Не нужно закрывать `img` тэги.

2023-01-26 08:12 UTC, vadimrahmanov commented on catalog.html
> +                  />
Не нужно закрывать `input` тэги.

2023-01-26 08:12 UTC, vadimrahmanov commented on catalog.html
> +                  />
Не нужно закрывать `input` тэги.

2023-01-26 08:12 UTC, vadimrahmanov commented on catalog.html
> +                  <input type="checkbox" name="wi-fi" class="control-input" />
Не нужно закрывать `input` тэги.

2023-01-26 08:12 UTC, vadimrahmanov commented on catalog.html
> +                  />
Не нужно закрывать `input` тэги.

2023-01-26 08:12 UTC, vadimrahmanov commented on catalog.html
> +                  <input type="radio" name="motel" class="control-input" />
Не нужно закрывать `input` тэги.

2023-01-26 08:12 UTC, vadimrahmanov commented on catalog.html
> +                  <input type="radio" name="apartments" class="control-input" />
Не нужно закрывать `input` тэги.

2023-01-26 08:12 UTC, vadimrahmanov commented on catalog.html
> +              <img src="" alt="" class="hotel-card-image" />
Не нужно закрывать `img` тэги.

2023-01-26 08:12 UTC, vadimrahmanov commented on catalog.html
> +              <img src="" alt="" class="hotel-card-image" />
Не нужно закрывать `img` тэги.

2023-01-26 08:12 UTC, vadimrahmanov commented on catalog.html
> +              <img src="" alt="" class="hotel-card-image" />
Не нужно закрывать `img` тэги.

2023-01-26 08:12 UTC, vadimrahmanov commented on catalog.html
> +              <img src="" alt="" class="hotel-card-image" />
Не нужно закрывать `img` тэги.

2023-01-26 08:12 UTC, vadimrahmanov commented on catalog.html
> +          />
Не нужно закрывать `input` тэги.

2023-01-26 08:12 UTC, vadimrahmanov commented on catalog.html
> +          <img src="" alt="Логотоп HTML-Академии" />
Не нужно закрывать `img` тэги.

2023-01-26 08:12 UTC, vadimrahmanov commented on index.html
> +              ><span class="visually-hidden">Поиск.</span></a
Закрывающую скобку не нужно переносить на новую строку, это касается всех мест на обоих страницах. Просто не хочу как с img, input и meta в каждом месте прописывать комментарий :D

2023-01-26 08:12 UTC, vadimrahmanov commented on index.html
> +        <img src="" alt="Вид на городок." />
Не нужно закрывать `img` тэги.

2023-01-26 08:12 UTC, vadimrahmanov commented on index.html
> +        </p>
Это не ошибка и так можно делать, но более читабельно будет, если всё-таки в таких случаях делать запись так:

` <p class="advantages-text">Рассмотрим причины, по которым Седона круче, чем Гранд-Каньон!</p>`

так как это просто текст, а не вложенный элемент внутрь другого.
Это касается всех мест в коде, где параграф или текст ссылки. Но если например текст был бы обёрнут в какой-нибудь `span`, то тогда это было бы правильно делать такое вложение.

2023-01-26 08:12 UTC, vadimrahmanov commented on index.html
> +      <a href="catalog.html" class="button">Поиск гостиницы в Седоне</a>
Это тоже можно вынести в секцию `Поиск гостиницы` :)

2023-01-26 08:12 UTC, vadimrahmanov commented on catalog.html
> +      </header>
Элемент `header` используется только для шапки страницы. Исключение: внутри тэга `<article>` допускается использовать тэг `<header>`.

Также необходимо вынести `h1` выше, так как это заголовок всей страницы.

2023-01-26 08:12 UTC, vadimrahmanov commented on catalog.html
> +        >
можно сделать какую-то обёртку типа `sort` или `sorting`

2023-01-26 08:12 UTC, vadimrahmanov commented on catalog.html
> +            </button>
`type="submit"` должен использоваться в форме. Здесь просто `type="button"`. Это касается всех карточек.

2023-01-26 20:00 UTC, oxxse commented on catalog.html
> +            </button>
Спасибо! Все замечания постаралась исправить.

2023-01-27 07:35 UTC, vadimrahmanov approved these changes

2023-01-27 07:35 UTC, vadimrahmanov commented on catalog.html
> +                  <input type="checkbox" name="wi-fi" class="control-input" />
Пропустила, когда убирала

2023-01-27 07:35 UTC, vadimrahmanov commented on catalog.html
> +              <img src="" alt="" class="hotel-card-image" />
Пропустила, когда убирала

2023-01-27 07:35 UTC, vadimrahmanov commented on index.html
> +        <img src="" alt="Каньон" />
Тут тоже пропустила, когда убирала /

2023-01-27 07:36 UTC, merged