Добавляет мелкие сетки
htmlacademy-htmlcss/2315875-sedona-36 pull request #6
Opened 2023-02-14 20:42 UTC by oxxse

2023-02-14 20:43 UTC, oxxse commented
Карточки товара оставила, чтобы сделать гридами в текущем разделе

2023-02-15 10:44 UTC, vadimrahmanov requested changes

2023-02-15 10:44 UTC, vadimrahmanov commented on catalog.html
> +                <button href="#" class="button-display-type">
У кнопки не может быть атрибута `href`

2023-02-15 10:44 UTC, vadimrahmanov commented on catalog.html
> +                <button href="#" class="button-display-type">
У кнопки не может быть атрибута `href`

2023-02-15 10:44 UTC, vadimrahmanov commented on catalog.html
> +        </ul>
По желанию: лучше сделать, чтобы было видно, что `span` вложен в ссылку. 

```
<a>
  <span></span>
</a>
```

2023-02-15 10:44 UTC, vadimrahmanov commented on styles/styles.css
> +
У тебя в разметке `page-header-logo` класс, эти свойства не работают. И ещё, не нужно задавать 

```
height: auto;
vertical-align:bottom;
```

просто задай `display: block` или `display: flex`

2023-02-15 10:44 UTC, vadimrahmanov commented on styles/styles.css
> +  margin:0;
пробел после `:`

2023-02-15 10:44 UTC, vadimrahmanov commented on styles/styles.css
> +  margin:0;
пробел после `:`

2023-02-15 14:25 UTC, vadimrahmanov approved these changes

2023-02-15 14:25 UTC, merged